/** Product control sections. Targets are read back by `readMosaicParams`. */

import type { ToolcraftControlSchema } from "@/toolcraft/runtime";

import { GIF_EXPORT_ACTION } from "./gif-export";
import { DEFAULT_PALETTE } from "./palettes";

export const SHUFFLE_ACTION = "mosaic.shuffle";

type Section = {
  controls: Record<string, ToolcraftControlSchema>;
  description?: string;
  id: string;
  title: string;
};

const always = { mode: "always" } as const;
const when = (target: string, value: unknown) =>
  ({ all: [{ equals: value, target }], mode: "conditional" }) as const;

const LIVE = "Live preview redraws the mosaic on every edit; the scene structure is cached.";
const STRUCTURE = "Rebuilds the cached tessellation and cell styles, then redraws.";

const bounded = { equals: false, target: "canvas.infinity" } as const;
const framing = (mode: "erosion" | "explosion") => ({ equals: mode, target: "frame.mode" }) as const;
const freeAspect = when("layout.square", false);
const grainOn = when("grain.gradient", true);
/** Runtime `semanticGroup` that places a product control inside Settings. */
const SETTINGS = "settings-product";

export const backgroundSection = {
  controls: {
    frameMode: {
      applicability: { all: [bounded], mode: "conditional" },
      defaultValue: "none",
      description: "Erosion deletes cells touching the outer frame; Explosion deletes random cells anywhere. Both leave transparent gaps (and turn Background off). Bounded canvas only.",
      label: "Framing",
      options: [
        { label: "None", value: "none" },
        { label: "Erosion", value: "erosion" },
        { label: "Explosion", value: "explosion" },
      ],
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      semanticGroup: SETTINGS,
      target: "frame.mode",
      type: "segmented",
    },
    edgeRemoval: {
      applicability: { all: [bounded, framing("erosion")], mode: "conditional" },
      defaultValue: 40,
      description: "Share of perimeter cells removed. Each cell has a fixed roll, so raising the amount only removes more.",
      label: "Erosion amount",
      max: 100,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      semanticGroup: SETTINGS,
      sliderValueKind: "continuous",
      step: 1,
      target: "frame.edgeRemoval",
      type: "slider",
      unit: "%",
    },
    explosionAmount: {
      applicability: { all: [bounded, framing("explosion")], mode: "conditional" },
      defaultValue: 25,
      description: "Share of cells deleted anywhere in the grid. Each cell has a fixed roll, so raising the amount only removes more.",
      label: "Explosion amount",
      max: 100,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      semanticGroup: SETTINGS,
      sliderValueKind: "continuous",
      step: 1,
      target: "frame.explosionAmount",
      type: "slider",
      unit: "%",
    },
    background: {
      applicability: always,
      defaultValue: "#FFFFFF",
      label: "Background color",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "appearance.background",
      type: "color",
    },
    includeBackground: {
      applicability: always,
      defaultValue: true,
      label: "Background",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "export.includeBackground",
      type: "switch",
    },
  },
  id: "background",
  title: "Background",
} satisfies Section;

export const gridSection = {
  controls: {
    seed: {
      applicability: always,
      defaultValue: 7,
      description: "Seeds the partition and every cell's colors, angles and fill mode.",
      label: "Seed",
      max: 999,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "layout.seed",
      type: "slider",
    },
    shuffle: {
      actions: [{ icon: "shuffle", label: "Shuffle", value: SHUFFLE_ACTION, variant: "secondary" }],
      applicability: always,
      label: "Variation",
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      target: "layout.shuffle",
      type: "actions",
    },
    square: {
      applicability: always,
      defaultValue: false,
      description: "1:1 aspect lock: packs the artboard with square cells sized by Cell width. Squares are exact when the artboard sides are whole multiples of the module (Module snap, or the minimum width).",
      label: "Square cells",
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      target: "layout.square",
      type: "switch",
    },
    cellWidth: {
      applicability: always,
      defaultValue: [160, 720],
      description: "Smallest and largest allowed cell width in canvas pixels (square side with Square cells on). Cuts keep every cell inside the limits whenever the artboard width allows it.",
      label: "Cell width",
      max: 1600,
      min: 16,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "layout.cellWidth",
      type: "rangeSlider",
      unit: "px",
    },
    cellHeight: {
      applicability: freeAspect,
      defaultValue: [160, 720],
      description: "Smallest and largest allowed cell height in canvas pixels. A narrow height range with a wide width range makes horizontal strips; the reverse makes columns.",
      label: "Cell height",
      max: 1600,
      min: 16,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "layout.cellHeight",
      type: "rangeSlider",
      unit: "px",
    },
    density: {
      applicability: always,
      defaultValue: 0.6,
      description: "Chance that a cell between the size limits keeps subdividing. With Square cells on, higher density favors smaller squares.",
      label: "Density",
      max: 1,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.density",
      type: "slider",
    },
    snap: {
      applicability: always,
      defaultValue: 0,
      description: "Snaps every cut to a module grid for a strict modular layout. 0 cuts freely.",
      label: "Module snap",
      max: 400,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "layout.snap",
      type: "slider",
      unit: "px",
    },
    varianceX: {
      applicability: freeAspect,
      defaultValue: 0.6,
      description: "How far vertical cuts may stray from the middle: 0 gives even columns, 1 very uneven widths.",
      label: "X variance",
      max: 1,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.varianceX",
      type: "slider",
    },
    varianceY: {
      applicability: freeAspect,
      defaultValue: 0.6,
      description: "How far horizontal cuts may stray from the middle: 0 gives even rows, 1 very uneven heights.",
      label: "Y variance",
      max: 1,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.varianceY",
      type: "slider",
    },
    splitBias: {
      applicability: freeAspect,
      defaultValue: 0,
      description: "Aspect bias: negative favors wide, row-like cells; positive favors tall, column-like cells.",
      label: "Aspect bias",
      max: 1,
      min: -1,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.splitBias",
      type: "slider",
    },
  },
  id: "grid",
  title: "Grid",
} satisfies Section;

export const paletteSection = {
  controls: {
    colors: {
      applicability: always,
      defaultValue: DEFAULT_PALETTE,
      hardMaxItems: 16,
      itemControl: { defaultValue: "#FFFFFF", type: "color" },
      label: "Colors",
      minItems: 1,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "palette.colors",
      type: "collectionActions",
    },
  },
  id: "palette",
  title: "Palette",
} satisfies Section;

const weight = (target: string, toggle: string, defaultValue: number) =>
  ({
    applicability: when(toggle, true),
    defaultValue,
    description: "Relative share of cells using this fill among the enabled modes.",
    label: "Weight",
    max: 10,
    min: 0,
    performanceReason: STRUCTURE,
    performanceRole: "responsiveness",
    sliderValueKind: "continuous",
    step: 0.1,
    target,
    type: "slider",
  }) satisfies ToolcraftControlSchema;

export const fillsSection = {
  controls: {
    solid: { applicability: always, defaultValue: true, label: "Solid", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.solid", type: "switch" },
    solidWeight: weight("fill.solidWeight", "fill.solid", 1),
    gradient: { applicability: always, defaultValue: true, label: "Gradient", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.gradient", type: "switch" },
    gradientWeight: weight("fill.gradientWeight", "fill.gradient", 4),
    gradientType: {
      applicability: when("fill.gradient", true),
      defaultValue: "mixed",
      label: "Gradient type",
      options: [
        { label: "Linear", value: "linear" },
        { label: "Radial", value: "radial" },
        { label: "Mixed", value: "mixed" },
      ],
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      target: "fill.gradientType",
      type: "segmented",
    },
    dither: { applicability: always, defaultValue: true, label: "Dither", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.dither", type: "switch" },
    ditherWeight: weight("fill.ditherWeight", "fill.dither", 0.6),
    ditherPattern: {
      applicability: when("fill.dither", true),
      defaultValue: "bayer",
      description: "Bayer: ordered 8×8 lattice. F-S: Floyd–Steinberg error diffusion. Random: white-noise threshold.",
      label: "Dither pattern",
      options: [
        { label: "Bayer", value: "bayer" },
        { label: "F-S", value: "fs" },
        { label: "Random", value: "random" },
      ],
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "fill.ditherPattern",
      type: "segmented",
    },
    ditherScale: {
      applicability: when("fill.dither", true),
      defaultValue: 4,
      description: "Size of one dither dot in canvas pixels.",
      label: "Dither dot",
      max: 32,
      min: 1,
      performanceReason: "Smaller dots raise the per-frame dither pixel count.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.ditherScale",
      type: "slider",
      unit: "px",
    },
    scanlines: { applicability: always, defaultValue: false, label: "Scanlines", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.scanlines", type: "switch" },
    scanlinesWeight: weight("fill.scanlinesWeight", "fill.scanlines", 1),
    scanlineDirection: {
      applicability: when("fill.scanlines", true),
      defaultValue: "horizontal",
      description: "Rows draws horizontal lines, Columns vertical lines; Mixed picks per cell.",
      label: "Direction",
      options: [
        { label: "Rows", value: "horizontal" },
        { label: "Columns", value: "vertical" },
        { label: "Mixed", value: "mixed" },
      ],
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      target: "fill.scanlineDirection",
      type: "segmented",
    },
    scanlineSpacing: {
      applicability: when("fill.scanlines", true),
      defaultValue: 12,
      description: "Line period in canvas pixels: one line plus one gap.",
      label: "Line spacing",
      max: 120,
      min: 2,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.scanlineSpacing",
      type: "slider",
      unit: "px",
    },
    scanlineThickness: {
      applicability: when("fill.scanlines", true),
      defaultValue: 50,
      description: "Share of each period covered by the line; the rest is an empty gap.",
      label: "Line weight",
      max: 95,
      min: 5,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.scanlineThickness",
      type: "slider",
      unit: "%",
    },
    scanlineTexture: {
      applicability: when("fill.scanlines", true),
      defaultValue: 60,
      description: "Print texture: each stroke swells and thins along its length, ink density drifts, and edges turn ragged. 0 gives flat digital stripes.",
      label: "Texture",
      max: 100,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.scanlineTexture",
      type: "slider",
      unit: "%",
    },
    dots: { applicability: always, defaultValue: false, label: "Dots", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.dots", type: "switch" },
    dotsWeight: weight("fill.dotsWeight", "fill.dots", 1),
    dotGrid: {
      applicability: when("fill.dots", true),
      defaultValue: "square",
      description: "Square aligns dots in rows and columns; Staggered offsets every other row by half a period.",
      label: "Dot grid",
      options: [
        { label: "Square", value: "square" },
        { label: "Staggered", value: "staggered" },
      ],
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "fill.dotGrid",
      type: "segmented",
    },
    dotSpacing: {
      applicability: when("fill.dots", true),
      defaultValue: 16,
      description: "Distance between dot centers in canvas pixels.",
      label: "Dot spacing",
      max: 160,
      min: 2,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.dotSpacing",
      type: "slider",
      unit: "px",
    },
    dotSize: {
      applicability: when("fill.dots", true),
      defaultValue: 60,
      description: "Dot diameter as a share of the spacing; 100% makes neighbors touch.",
      label: "Dot size",
      max: 100,
      min: 5,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.dotSize",
      type: "slider",
      unit: "%",
    },
    ascii: { applicability: always, defaultValue: false, label: "ASCII", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.ascii", type: "switch" },
    asciiWeight: weight("fill.asciiWeight", "fill.ascii", 1),
    asciiChar: {
      applicability: when("fill.ascii", true),
      defaultValue: "*",
      description: "The glyph tiled across ASCII cells. Only the first character is used.",
      label: "Character",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "fill.asciiChar",
      type: "text",
    },
    asciiSize: {
      applicability: when("fill.ascii", true),
      defaultValue: 24,
      description: "Glyph size in canvas pixels. Glyphs sit on a uniform monospace grid: 0.6 em wide, 1 em tall.",
      label: "Glyph size",
      max: 160,
      min: 4,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.asciiSize",
      type: "slider",
      unit: "px",
    },
  },
  description: "Each cell draws one enabled fill mode, picked by weight. Scanlines, dots and ASCII draw only their marks in one palette color; the rest of the cell stays empty, showing the Background (or transparency).",
  id: "fills",
  title: "Fills",
} satisfies Section;

export const motionSection = {
  controls: {
    drift: {
      applicability: always,
      defaultValue: 0.5,
      description: "How far gradient midpoints and radial centers drift through each loop.",
      label: "Stop drift",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "motion.drift",
      type: "slider",
    },
    colorBreath: {
      applicability: always,
      defaultValue: 0.6,
      description: "How far each gradient cell's stop colors drift toward other palette hues over the loop. Blends are perceptual (OKLab) and continuous.",
      label: "Color breath",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "motion.colorBreath",
      type: "slider",
    },
    hueSteps: {
      applicability: always,
      defaultValue: 1,
      description: "Number of palette hues each gradient stop visits per loop before returning home.",
      label: "Hue steps",
      max: 6,
      min: 1,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "motion.hueSteps",
      type: "slider",
      variant: "discrete",
    },
    ditherScroll: {
      applicability: always,
      defaultValue: 1,
      description: "Pattern periods the dither, scanline, dot and ASCII lattices shift per loop.",
      label: "Pattern scroll",
      max: 8,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "motion.ditherScroll",
      type: "slider",
      variant: "discrete",
    },
  },
  description: "All motion is periodic in the timeline loop, so exports loop seamlessly. Cell geometry never rotates.",
  id: "motion",
  title: "Motion",
} satisfies Section;

export const grainSection = {
  controls: {
    enabled: {
      applicability: always,
      defaultValue: true,
      description: "Grain is screened into gradient cells only; solid, dither, scanline, dot and ASCII cells stay clean.",
      label: "Gradient grain",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "grain.gradient",
      type: "switch",
    },
    amount: {
      applicability: grainOn,
      defaultValue: 0.5,
      description: "How strongly the grain screens each cell's inks. It turns gradient tone into specks.",
      label: "Intensity",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "grain.amount",
      type: "slider",
    },
    discreteness: {
      applicability: grainOn,
      defaultValue: 0.85,
      description: "0 gives a soft, blurred mottle blended into the color; 1 gives crisp, quantized particles.",
      label: "Discreteness",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "grain.discreteness",
      type: "slider",
    },
    size: {
      applicability: grainOn,
      defaultValue: 1,
      description: "Size of one grain speck in canvas pixels.",
      label: "Grain size",
      max: 12,
      min: 0.5,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.25,
      target: "grain.size",
      type: "slider",
      unit: "px",
    },
    speed: {
      applicability: grainOn,
      defaultValue: 2,
      description: "Times each grain speck re-inks per loop. Specks flip at staggered moments, so the grain twinkles while staying crisp; whole cycles keep the loop seamless. 0 freezes it.",
      label: "Shimmer",
      max: 12,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "grain.speed",
      type: "slider",
      variant: "discrete",
    },
  },
  description: "Risograph grain screened into gradient cells.",
  id: "grain",
  title: "Grain",
} satisfies Section;

export const gifSection = {
  controls: {
    fps: {
      applicability: always,
      defaultValue: 15,
      description: "GIF frame rate. The GIF always spans exactly one timeline loop.",
      label: "Frame rate",
      max: 30,
      min: 5,
      performanceReason: "Frame count scales GIF render and encode time.",
      performanceRole: "workload",
      sliderValueKind: "continuous",
      step: 1,
      target: "gif.fps",
      type: "slider",
      unit: "fps",
    },
    width: {
      applicability: always,
      defaultValue: "640",
      label: "Width",
      options: [
        { label: "480 px", value: "480" },
        { label: "640 px", value: "640" },
        { label: "960 px", value: "960" },
        { label: "1280 px", value: "1280" },
      ],
      performanceReason: "Pixel count scales GIF render and encode time.",
      performanceRole: "workload",
      target: "gif.width",
      type: "select",
    },
  },
  id: "gif-export",
  title: "GIF Export",
} satisfies Section;

/** Action-only section: runtime merges it into the sticky export footer. */
export const gifActionSection = {
  controls: {
    exportGif: {
      actions: [{ icon: "download-simple", label: "Export GIF", value: GIF_EXPORT_ACTION, variant: "outline" }],
      applicability: always,
      target: "gif.export",
      type: "panelActions",
    },
  },
  id: "gif-actions",
  title: "Export",
} satisfies Section;

export const mosaicSections = [
  backgroundSection,
  gridSection,
  paletteSection,
  fillsSection,
  motionSection,
  grainSection,
  gifSection,
  gifActionSection,
];
