/** Product control sections. Targets are read back by `readMosaicParams`. */

import type { ToolcraftControlSchema } from "@/toolcraft/runtime";

import { GIF_EXPORT_ACTION } from "./gif-export";
import { DEFAULT_PALETTE } from "./palettes";

export const SHUFFLE_ACTION = "mosaic.shuffle";

type Section = {
  controls: Record<string, ToolcraftControlSchema>;
  description?: string;
  id: string;
  title: string;
};

const always = { mode: "always" } as const;
const when = (target: string, value: unknown) =>
  ({ all: [{ equals: value, target }], mode: "conditional" }) as const;

const LIVE = "Live preview redraws the mosaic on every edit; the scene structure is cached.";
const STRUCTURE = "Rebuilds the cached tessellation and cell styles, then redraws.";

const bounded = { equals: false, target: "canvas.infinity" } as const;
/** Runtime `semanticGroup` that places a product control inside Settings. */
const SETTINGS = "settings-product";

export const backgroundSection = {
  controls: {
    explode: {
      applicability: { all: [bounded], mode: "conditional" },
      defaultValue: false,
      description: "Prunes cells touching the outer frame into transparent gaps (turns Background off). Bounded canvas only.",
      label: "Explode Edges",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      semanticGroup: SETTINGS,
      target: "frame.explode",
      type: "switch",
    },
    edgeRemoval: {
      applicability: { all: [bounded, { equals: true, target: "frame.explode" }], mode: "conditional" },
      defaultValue: 40,
      description: "Share of perimeter cells removed. Each cell has a fixed roll, so raising the amount only removes more.",
      label: "Edge Removal Amount",
      max: 100,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      semanticGroup: SETTINGS,
      sliderValueKind: "continuous",
      step: 1,
      target: "frame.edgeRemoval",
      type: "slider",
      unit: "%",
    },
    background: {
      applicability: always,
      defaultValue: "#FFFFFF",
      label: "Background color",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "appearance.background",
      type: "color",
    },
    includeBackground: {
      applicability: always,
      defaultValue: true,
      label: "Background",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "export.includeBackground",
      type: "switch",
    },
  },
  id: "background",
  title: "Background",
} satisfies Section;

export const gridSection = {
  controls: {
    seed: {
      applicability: always,
      defaultValue: 7,
      description: "Seeds the partition and every cell's colors, angles and fill mode.",
      label: "Seed",
      max: 999,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "layout.seed",
      type: "slider",
    },
    shuffle: {
      actions: [{ icon: "shuffle", label: "Shuffle", value: SHUFFLE_ACTION, variant: "secondary" }],
      applicability: always,
      label: "Variation",
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      target: "layout.shuffle",
      type: "actions",
    },
    cellSize: {
      applicability: always,
      defaultValue: [160, 720],
      description: "Smallest and largest allowed cell edge in canvas pixels. Cells larger than the maximum always split; cells are never cut below the minimum.",
      label: "Cell size",
      max: 1600,
      min: 16,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "layout.cellSize",
      type: "rangeSlider",
      unit: "px",
    },
    density: {
      applicability: always,
      defaultValue: 0.6,
      description: "Chance that a cell between the size limits keeps subdividing.",
      label: "Density",
      max: 1,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.density",
      type: "slider",
    },
    snap: {
      applicability: always,
      defaultValue: 0,
      description: "Snaps every cut to a module grid for a strict modular layout. 0 cuts freely.",
      label: "Module snap",
      max: 400,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "layout.snap",
      type: "slider",
      unit: "px",
    },
    varianceX: {
      applicability: always,
      defaultValue: 0.6,
      description: "How far vertical cuts may stray from the middle: 0 gives even columns, 1 very uneven widths.",
      label: "X variance",
      max: 1,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.varianceX",
      type: "slider",
    },
    varianceY: {
      applicability: always,
      defaultValue: 0.6,
      description: "How far horizontal cuts may stray from the middle: 0 gives even rows, 1 very uneven heights.",
      label: "Y variance",
      max: 1,
      min: 0,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.varianceY",
      type: "slider",
    },
    splitBias: {
      applicability: always,
      defaultValue: 0,
      description: "Aspect bias: negative favors wide, row-like cells; positive favors tall, column-like cells.",
      label: "Aspect bias",
      max: 1,
      min: -1,
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "layout.splitBias",
      type: "slider",
    },
  },
  id: "grid",
  title: "Grid",
} satisfies Section;

export const paletteSection = {
  controls: {
    colors: {
      applicability: always,
      defaultValue: DEFAULT_PALETTE,
      hardMaxItems: 16,
      itemControl: { defaultValue: "#FFFFFF", type: "color" },
      label: "Colors",
      minItems: 1,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "palette.colors",
      type: "collectionActions",
    },
  },
  id: "palette",
  title: "Palette",
} satisfies Section;

const weight = (target: string, toggle: string, defaultValue: number) =>
  ({
    applicability: when(toggle, true),
    defaultValue,
    description: "Relative share of cells using this fill among the enabled modes.",
    label: "Weight",
    max: 10,
    min: 0,
    performanceReason: STRUCTURE,
    performanceRole: "responsiveness",
    sliderValueKind: "continuous",
    step: 0.1,
    target,
    type: "slider",
  }) satisfies ToolcraftControlSchema;

export const fillsSection = {
  controls: {
    solid: { applicability: always, defaultValue: true, label: "Solid", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.solid", type: "switch" },
    solidWeight: weight("fill.solidWeight", "fill.solid", 1),
    gradient: { applicability: always, defaultValue: true, label: "Gradient", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.gradient", type: "switch" },
    gradientWeight: weight("fill.gradientWeight", "fill.gradient", 4),
    gradientType: {
      applicability: when("fill.gradient", true),
      defaultValue: "mixed",
      label: "Gradient type",
      options: [
        { label: "Linear", value: "linear" },
        { label: "Radial", value: "radial" },
        { label: "Mixed", value: "mixed" },
      ],
      performanceReason: STRUCTURE,
      performanceRole: "responsiveness",
      target: "fill.gradientType",
      type: "segmented",
    },
    dither: { applicability: always, defaultValue: true, label: "Dither", performanceReason: STRUCTURE, performanceRole: "responsiveness", target: "fill.dither", type: "switch" },
    ditherWeight: weight("fill.ditherWeight", "fill.dither", 0.6),
    ditherPattern: {
      applicability: when("fill.dither", true),
      defaultValue: "bayer",
      description: "Bayer: ordered 8×8 lattice. F-S: Floyd–Steinberg error diffusion. Random: white-noise threshold.",
      label: "Dither pattern",
      options: [
        { label: "Bayer", value: "bayer" },
        { label: "F-S", value: "fs" },
        { label: "Random", value: "random" },
      ],
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "fill.ditherPattern",
      type: "segmented",
    },
    ditherScale: {
      applicability: when("fill.dither", true),
      defaultValue: 4,
      description: "Size of one dither dot in canvas pixels.",
      label: "Dot size",
      max: 32,
      min: 1,
      performanceReason: "Smaller dots raise the per-frame dither pixel count.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "fill.ditherScale",
      type: "slider",
      unit: "px",
    },
  },
  description: "Each cell draws one enabled fill mode, picked by weight.",
  id: "fills",
  title: "Fills",
} satisfies Section;

export const motionSection = {
  controls: {
    drift: {
      applicability: always,
      defaultValue: 0.5,
      description: "How far gradient midpoints and radial centers drift through each loop.",
      label: "Stop drift",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "motion.drift",
      type: "slider",
    },
    colorBreath: {
      applicability: always,
      defaultValue: 0.6,
      description: "How far each gradient cell's stop colors drift toward other palette hues over the loop. Blends are perceptual (OKLab) and continuous.",
      label: "Color breath",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "motion.colorBreath",
      type: "slider",
    },
    hueSteps: {
      applicability: always,
      defaultValue: 1,
      description: "Number of palette hues each gradient stop visits per loop before returning home.",
      label: "Hue steps",
      max: 6,
      min: 1,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "motion.hueSteps",
      type: "slider",
      variant: "discrete",
    },
    ditherScroll: {
      applicability: always,
      defaultValue: 1,
      description: "Dither pattern periods the lattice shifts per loop.",
      label: "Dither scroll",
      max: 8,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "motion.ditherScroll",
      type: "slider",
      variant: "discrete",
    },
  },
  description: "All motion is periodic in the timeline loop, so exports loop seamlessly. Cell geometry never rotates.",
  id: "motion",
  title: "Motion",
} satisfies Section;

export const grainSection = {
  controls: {
    onGradient: {
      applicability: always,
      defaultValue: true,
      label: "Gradients",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "grain.gradient",
      type: "checkbox",
    },
    onDither: {
      applicability: always,
      defaultValue: true,
      label: "Dithers",
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      target: "grain.dither",
      type: "checkbox",
    },
    amount: {
      applicability: always,
      defaultValue: 0.5,
      description: "How strongly the grain screens each cell's inks. On gradients it turns tone into specks; on dithers it erodes and sprinkles the dots. Solid cells stay clean.",
      label: "Intensity",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "grain.amount",
      type: "slider",
    },
    discreteness: {
      applicability: always,
      defaultValue: 0.85,
      description: "0 gives a soft, blurred mottle blended into the color; 1 gives crisp, quantized particles.",
      label: "Discreteness",
      max: 1,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "grain.discreteness",
      type: "slider",
    },
    size: {
      applicability: always,
      defaultValue: 1,
      description: "Size of one grain speck in canvas pixels.",
      label: "Grain size",
      max: 12,
      min: 0.5,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.25,
      target: "grain.size",
      type: "slider",
      unit: "px",
    },
    speed: {
      applicability: always,
      defaultValue: 2,
      description: "Times each grain speck re-inks per loop. Specks flip at staggered moments, so the grain twinkles while staying crisp; whole cycles keep the loop seamless. 0 freezes it.",
      label: "Shimmer",
      max: 12,
      min: 0,
      performanceReason: LIVE,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "grain.speed",
      type: "slider",
      variant: "discrete",
    },
  },
  description: "Risograph grain screened into gradient and/or dither cells.",
  id: "grain",
  title: "Grain",
} satisfies Section;

export const gifSection = {
  controls: {
    fps: {
      applicability: always,
      defaultValue: 15,
      description: "GIF frame rate. The GIF always spans exactly one timeline loop.",
      label: "Frame rate",
      max: 30,
      min: 5,
      performanceReason: "Frame count scales GIF render and encode time.",
      performanceRole: "workload",
      sliderValueKind: "continuous",
      step: 1,
      target: "gif.fps",
      type: "slider",
      unit: "fps",
    },
    width: {
      applicability: always,
      defaultValue: "640",
      label: "Width",
      options: [
        { label: "480 px", value: "480" },
        { label: "640 px", value: "640" },
        { label: "960 px", value: "960" },
        { label: "1280 px", value: "1280" },
      ],
      performanceReason: "Pixel count scales GIF render and encode time.",
      performanceRole: "workload",
      target: "gif.width",
      type: "select",
    },
  },
  id: "gif-export",
  title: "GIF Export",
} satisfies Section;

/** Action-only section: runtime merges it into the sticky export footer. */
export const gifActionSection = {
  controls: {
    exportGif: {
      actions: [{ icon: "download-simple", label: "Export GIF", value: GIF_EXPORT_ACTION, variant: "outline" }],
      applicability: always,
      target: "gif.export",
      type: "panelActions",
    },
  },
  id: "gif-actions",
  title: "Export",
} satisfies Section;

export const mosaicSections = [
  backgroundSection,
  gridSection,
  paletteSection,
  fillsSection,
  motionSection,
  grainSection,
  gifSection,
  gifActionSection,
];
